### ISSUE TITLE
Minify transform properties breaks animations

### ISSUE THREAD

**Issue by oscarotero** [wilsonzlin/minify-html#173]
I have the following css code:

```css
@keyframes firecircle {
    0% {
      transform: translateY(0) scale(1);
    }

    100% {
      transform: translateY(-11em) scale(0);
    }
  }
```
That is minified to:

```css
@keyframes firecircle{0%{transform:matrix(1,0,0,1,0,0)}to{transform:translateY(-11em)scale(0)}}
```

As you can see, the value in the first step is transformed to a `matrix` and the animation no longer works.

This happens after updating to the latest version (0.15.0). Before that, I was using 0.11.1 and it worked fine.
