### ISSUE TITLE
Not working on Windows ARM

### ISSUE THREAD

**Issue by kireerik** [wilsonzlin/minify-html#226]
I am getting the following error:
```
Error: Cannot find module '@minify-html/node-win32-arm64'
```

similar issue:
- #172

**Comment by wilsonzlin** [comment]
There's no support for Windows ARM64, as mentioned in the README under the Node.js section.

This is due to lack of easy way to do this cross-arch targeting in the current Windows GitHub Actions runner.

**Comment by kireerik** [comment]
I see.

Maybe adding it at the following places can work:
https://github.com/wilsonzlin/minify-html/blob/2301223773dadce30a33b4c407d8b2524adeb5e2/.github/workflows/nodejs.yml#L19-L30
```yml
          - arm64-pc-windows-msvc          
          - x86_64-pc-windows-msvc
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: aarch64-apple-darwin
            os: macos-13
          - target: x86_64-apple-darwin
            os: macos-13
          - target: arm64-pc-windows-msvc
            os: windows-2022
          - target: x86_64-pc-windows-msvc
            os: windows-2019
```
https://github.com/wilsonzlin/minify-html/blob/2301223773dadce30a33b4c407d8b2524adeb5e2/minify-html-nodejs/plat-pkg/package.json.gen.js#L6
```JavaScript
  "arm64-pc-windows-msvc": {platform: "win32", arch: "arm64"},
  "x86_64-pc-windows-msvc": {platform: "win32", arch: "x64"},
```
https://github.com/wilsonzlin/minify-html/blob/2301223773dadce30a33b4c407d8b2524adeb5e2/minify-html-nodejs/package.json#L44
```JSON
    "@minify-html/node-win32-arm64": "0.16.4"
    "@minify-html/node-win32-x64": "0.16.4"
```

The fact that currently there is no Windows ARM GitHub Actions runner is might not an issue.

Otherwise as a temporary workaround instead of an error we could throw a warning and use the x64 module as a fallback (until there is no dedicated ARM module). I think that module should work as is on Windows ARM as well.

What do you think?
